easy_admin:

 
    entities:
        # List the entity class name you want to manage
       Demande:
           class: App\Entity\Demande
           form:
                fields:
                    - materiel
                    - quantite
                    - dateDemande
                    - tempsDemande
                    - message
                    - { property: 'livraison', label: 'Livraison'  ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Livraison' } }
        
       Offre:
           class: App\Entity\Offre
           form:
                fields:
                    - materiel
                    - quantite
                    - dateOffre
                    - timeOffre
                    - message
                    - { property: 'livraison', label: 'Livraison'  ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Livraison' } }
                    
       Livraison:
            class: App\Entity\Livraison
           


       User: 
            display_name: true
            display_property_path: 'username'
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - profession
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }


    site_name: 'DOCOVID'
    
    design:
        menu: 
            - {label: "Entités"}
            - label: "Demande"
              children:
                    - {entity: Demande, label: "Liste des demandes", icon: "th-list"}
                    - {entity: Demande, label: "Ajouter Demande", icon: "plus", params: {action: 'new'}}
                    - label: "Demande"
            - label: "Offre"
              children:
                    - {entity: Offre, label: "Liste des offres", icon: "th-list"}
                    - {entity: Offre, label: "Ajouter Offre", icon: "plus", params: {action: 'new'}}
            - label: "Livraison"
              children:
                    - {entity: Livraison, label: "Liste des Livraisons", icon: "th-list"}
                    - {entity: Livraison, label: "Ajouter Livraison", icon: "plus"}
            - {label: "Paramètres"}
            - {entity: User, icon: "user"}

