easy_admin:

 
    entities:
        # List the entity class name you want to manage
       Demande:
           class: App\Entity\Demande

       Livraison:
            class: App\Entity\Livraison

       User: 
            display_name: true
            display_property_path: 'username'
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }


    site_name: 'DOCOVID'
    
    design:
        menu:
            - {label: "Entités"}
            - label: "Demande"
              children:
                    - {entity: Demande, label: "Liste des demandes", icon: "th-list"}
                    - {entity: Demande, label: "Ajouter Demande", icon: "plus", params: {action: 'new'}}
            - label: "Livraison"
              children:
                    - {entity: Livraison, label: "Liste des Livraisons", icon: "th-list"}
                    - {entity: Livraison, label: "Ajouter Livraison", icon: "plus"}
            - {label: "Paramètres"}
            - {entity: User, icon: "user"}

